### ISSUE TITLE
how to override col_spec

### ISSUE THREAD

**Issue by fredzannarbor** [asehmi/auth-simple-for-streamlit#3]
Hi,

I need to add some more columns to my USERS table and be able to query them.  Is there a way that I can override col_spec without modifying your code?

https://github.com/asehmi/auth-simple-for-streamlit/blob/86472f31f78eabcee8458f48fdac39a48e6ae6e8/authlib/repo/provider/sqlite/implementation.py#L35

**Comment by asehmi** [comment]
I haven't implemented that. This code is supposed to be taken as-is and modified to suit your needs. For easier extensibility, I'd suggest you use the AIRTABLE provider. Having said that, the table creation code is really all you need to touch in the SQLITE provider, perhaps adding a [roles] column. If your needs are getting beyond this, then you need an identity solution, not a login auth solution, which is what this is. You can also make a few little changes so the success login token is returned with the roles data. HTH.
