### ISSUE TITLE
how to set a cookie?

### ISSUE THREAD

**Issue by fredzannarbor** [asehmi/auth-simple-for-streamlit#5]
How can I set a cookie to save the login status?  I see from a little internet research that there is a python library called cookie-jar that uses the Netscape format, is that a safe choice? Would I just modify the login dialog to check if there is a cookie set on first attempt and then act accordingly?

**Comment by asehmi** [comment]
Hi - this repo has been updated to support cookies. Contribution by @ch-saeki https://github.com/asehmi/auth-simple-for-streamlit/commit/eec7d763b9d335c67a2801c6b25211de347570bb
